# Axel '0vercl0k' Souchet - April 19 2020
version: 1.0.{build}

image:
  - Visual Studio 2019

configuration:
  - RelWithDebInfo
  - Debug

platform:
  - x86
  - x64

clone_folder: c:\projects\kdmp-parser

build_script:
  - cmd: C:\Python38-x64\python.exe builder.py --configuration %configuration% --arch %platform% --run-tests

after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: 7z a -t7z kdmp-parser-%platform%.%configuration%.7z bin\%platform%-%configuration%\*
  - cmd: chdir

artifacts:
  - path: kdmp-parser-*.7z

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
