# Axel '0vercl0k' Souchet - July 26 2020
name: Builds

on: [push, pull_request]

jobs:
  Linux2004Gcc:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt install -y g++-10 g++-multilib ninja-build

    - name: Build
      run: CC=gcc-10 CXX=g++-10 python3 builder.py --run-tests

    - name: Upload artifacts for rel/x64
      uses: actions/upload-artifact@v2
      with:
        name: linx64-RelWithDebInfo
        path: bin/linx64-RelWithDebInfo

    - name: Upload artifacts for dbg/x64
      uses: actions/upload-artifact@v2
      with:
        name: linx64-Debug
        path: bin/linx64-Debug

  Windows:
    name: Windows latest
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Setup vs prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: python builder.py --run-tests

    - name: Upload artifacts for rel/x64
      uses: actions/upload-artifact@v2
      with:
        name: winx64-RelWithDebInfo
        path: bin/winx64-RelWithDebInfo

    - name: Upload artifacts for dbg/x64
      uses: actions/upload-artifact@v2
      with:
        name: winx64-Debug
        path: bin/winx64-Debug