name: Builds

on: [push, pull_request]

jobs:
  Linux2004Gcc:
    name: Ubuntu 20.04 / GCC10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt install -y g++-10 ninja-build

    - name: Build
      run: |
        python3 builder.py --configuration RelWithDebInfo --arch x64 --run-tests
        python3 builder.py --configuration RelWithDebInfo --arch x86 --run-tests
