# Axel '0vercl0k' Souchet - July 26 2020
name: Builds

on: [push, pull_request]

jobs:
  Linux2004Gcc:
    name: Ubuntu 20.04 / GCC10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt install -y g++-multilib ninja-build

    - name: Build
      run: |
        python3 builder.py --run-tests

  Windows:
    name: Windows latest
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: python3 builder.py --run-tests
